[package]
name = "rgb-benchmark"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
image.workspace = true
pollster.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu.workspace = true
sim-graphics = { path = "../../crates/sim-graphics" }
